name: "Sync docs"
description: "Sync the documentation sites after the release"

runs:
  using: composite
  steps:
    - name: Fetch latest from origin
      run: git fetch origin
      shell: bash

    - name: Sync docs
      run: |
        pnpm gen:docs
        pnpm --prefix docs get:theme
        pnpm --prefix docs get:props
        pnpm --prefix docs get:changelog
        pnpm --prefix docs get:styled-system
        pnpm --prefix docs get:contributors
        pnpm --prefix docs get:search
        pnpm --prefix docs get:icons
      shell: bash

    - name: Create PR
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ env.GITHUB_TOKEN }}
        base: documentation
        commit-message: "ci(changesets): sync documentation"
        title: "Sync documentation"
        branch: changeset-release/docs
        assignees: "hirotomoyamada"
        reviewers: "hirotomoyamada"
